### ISSUE TITLE
Theme main color doesn't apply to certain buttons/elements

### ISSUE THREAD

**Issue by razvanaldea89** [ColorlibHQ/Bakery#6]

**Comment by codepixar** [comment]
Fixed

**Comment by razvanaldea89** [comment]
Not everywhere.

![horseclub main color](https://user-images.githubusercontent.com/44024114/59087144-8bd33b80-890c-11e9-8ee9-b359ca327fbf.PNG)

**Comment by codepixar** [comment]
Make sure that is this Bakery theme? Maybe this is "Horseclub" theme.

**Comment by razvanaldea89** [comment]
Yeah, sorry about that :)
